dist: trusty
sudo: false
language: node_js
node_js:
  - '6'
  - '8'
cache: yarn
before_deploy:
  - cd ./dist
deploy:
  provider: npm
  email: felix@stkn.org
  api_key:
    secure: KoD24xE74PqJnd+f1IHOXWW6N29CgGc3zzwMW8XCO6ejl2aVhyWqmdNNq3SYrUcAE16X4pxTZZgZOX1JIrjdrM4a+TVQeNdbkQQugD6i5PzWebEcJPHxktNIlRLPahBtHqy0d6UnJY6PFntm9SfRd30/CUkNUAj85YQg/G6WYFqiDum4cr4iTIASWiLy8OTKMXTjm0VLn4PMJoTTYVbHHOE4BoLgjKKmOyeMNHGllrWTnUNNGDYiHg1p9gRCb+o5FKky+jtHzUN1PJdy1o2lVb/8qJSYeV9mjqQWyezFKSGwJJzLKLIowhT3hoL12y5Kmw/7yTjgSKWGhtf6JAXZCHJmEq4qo7tZv4LlV4M8cwIraEqyyH6ahw2TFE6TFkkwZFe8hEfpcZzzyOIL4vxP59y896ndNGG4CwuoWtss2hx3K2Ff7i05SAQlzwomuk7Ti1gPCMVs4NTRw2FvJtkvPvAf7w6DP+krsm5iw/RmPmfvM6qDXnkcuLGaErT/zcQf6FnB3uV7dsjjy8iNxh1PDZF689/CsUxAsdZ0jZqk1giTcyiqOiDNVyFrw78yP0lkuG/VxNuOLmHiyjUU6AOuSEaRpDJyjglEQG9H0d55/gvDbhtUmt+sejKYARAhw4Mf/IAiog4K9Cunfg0mNk89KVZk23xrdxXvIQUOCs6FR4o=
  on:
    tags: true
    repo: cebor/angular-highcharts
