sudo: false
language: node_js
node_js: 10
cache: yarn
script:
  - npm run build_lib
before_deploy:
  - cd ./dist/angular-highcharts
deploy:
  skip_cleanup: true
  provider: npm
  email: felix@stkn.org
  api_key:
    secure: TkxY9K3Cv5lc7Ez6iyYGiM2mD1BagsgRdvXdU9e8XoAtp+mOqqpxEpAXCeyv5lK6fuRBpK53v0FHDAjLnLHMCn6+18NmWyQj/7z9dVIJdb7rQjCiOQ5TlKRYRcLN3M/02kWqkMbh0i01Cqxu5VjSLSDf2/ZxxJyE1L5VkrdnipQKDsRmVRWOdjqlqY7z4qAg5UPHo4GvDnUPBnrwabfdo4ewWTQmLHIits49IJtNB6JI+nRxErcpqC8iOpjRZRDuO6rL+4hmzgZLLyNCRlxYJMHyBC5ZsfrNNORLt6Mi14RY2cf5f6oYqNAw7ljYcscUqd9GcYrvgNnfetexsoKkW8IvD49CYPq13PEIatVTIVVzM8AmsLaI3+DXnvUEkyaLCGkrGviJ6jq2LtebeoE92BeJFEGwmUwdLOmGe6jGt6LfeLOZD5MnfZf8YM7G57h7ouGjSy/9kC4M8XahWct0Zb8jCRTvEEOzIBS5VdnbpJ+Eu4XrixNjQsCLm0OHwioSqC80vlNnkWOrZRbjVJtN7W+Y13rVWr8gITgUTNIwIpIwh5XPHSagttZSn07lD/rOLeupmG8z0P5j4Sp5KaeBHGH6ukcV543npaSt//iqLVXHbNMx98hjKsryZOB/u7fF3g15TL0LhqwTw3pdvhdhiZvYCZRq2bwjp6oth0DymKw=
  on:
    tags: true
    repo: cebor/angular-highcharts
